"""FRR config templates, shared by the generator and the demo-pod builder.

Deliberately free of imports. `labtris_api/__init__` pulls in the whole
application, so anything that reaches these through the package needs FastAPI
and a database driver installed — which `packaging/demo-pods/build-ai-pods.py`
has no business requiring. Keeping this module importable by file path is what
lets the pods ship the same config the generator writes instead of a second
copy that drifts.
"""

from __future__ import annotations


def _frr_installer(daemons: str, frr_conf: str, pre: str = '') -> str:
    """Wrap the FRR daemons + frr.conf as a self-installing shell script.

    push_config already writes startup_config to /config/startup-config
    inside the container; running `sh /config/startup-config` there
    then applies the config in place. Two-step from the user:

        labtris node push <id>
        labtris node exec <id> -- sh /config/startup-config

    Kept as one file rather than two writes because the container has
    exactly one startup_config slot today. When per-node bind mounts on
    the FRR profile land (Phase F5+), this becomes native — the
    generator writes straight to `/etc/frr/` and reload is automatic.
    """
    return f"""#!/bin/sh
# Generated by `labtris lab generate --with-bgp-evpn`.
# Push with: labtris node push <this-node>
# Apply with: labtris node exec <this-node> -- sh /config/startup-config
set -e
{pre}
mkdir -p /etc/frr
cat > /etc/frr/daemons.new <<'EOF_DAEMONS'
{daemons}
EOF_DAEMONS
cat > /etc/frr/frr.conf <<'EOF_FRR'
{frr_conf}
EOF_FRR
# vtysh looks for this and complains on stderr for every single command when
# it is absent:
#
#   % Can't open configuration file /etc/frr/vtysh.conf due to 'No such file
#   or directory'.
#
# Harmless, and noise on every `show` an operator runs — it also has to be
# filtered out of anything that parses vtysh output, which is a silly thing to
# make a caller do. integrated-vtysh-config is the mode this config already
# assumes: one frr.conf rather than per-daemon files.
cat > /etc/frr/vtysh.conf <<'EOF_VTYSH'
service integrated-vtysh-config
EOF_VTYSH
chown -R frr:frr /etc/frr 2>/dev/null || true

# Restart only when a restart is actually required; otherwise reload.
#
# This was an unconditional `frrinit.sh restart`, for a good reason: the image
# entrypoint runs `frrinit.sh start` against a daemons file that still says
# bgpd=no, so `start` is a no-op, bgpd never launches, and the fabric
# generates correct config and never converges. Only a restart re-reads the
# daemons file.
#
# But restarting is catastrophic on a fabric that has already converged. It
# drops every session on the node, and each drop is seen by all its peers,
# which re-advertise to theirs. On a k=22 fat tree one edge restart touches
# roughly 253 adjacencies, so applying config to 242 edges sixteen at a time
# put about 4000 adjacency events in flight and pinned all 24 cores for long
# enough to starve sshd off the box.
#
# A restart is only needed when the daemons file itself changed — which is
# true on the first apply and false on every one after it. So compare, and
# reload when the daemon set is unchanged. `reload` runs frr-reload.py, which
# diffs the running config against the new one and applies only the
# difference: no session teardown, no reconvergence.
NEED_RESTART=no
if ! /usr/lib/frr/frrinit.sh status >/dev/null 2>&1; then
  # Nothing running to reload into.
  NEED_RESTART=yes
elif ! cmp -s /etc/frr/daemons.new /etc/frr/daemons 2>/dev/null; then
  NEED_RESTART=yes
fi
mv -f /etc/frr/daemons.new /etc/frr/daemons
chown frr:frr /etc/frr/daemons 2>/dev/null || true
if [ "$NEED_RESTART" = yes ]; then
  /usr/lib/frr/frrinit.sh restart
elif ! /usr/lib/frr/frrinit.sh reload; then
  # frr-reload.py refuses changes it cannot express incrementally. Falling
  # back is correct but expensive, so it says so rather than doing it quietly.
  echo "reload declined the diff; restarting instead" >&2
  /usr/lib/frr/frrinit.sh restart
fi
"""


_FRR_DAEMONS_EVPN = """\
bgpd=yes
ospfd=no
ospf6d=no
ripd=no
ripngd=no
isisd=no
pimd=no
ldpd=no
nhrpd=no
eigrpd=no
babeld=no
sharpd=no
pbrd=no
bfdd=no
fabricd=no
vrrpd=no
pathd=no
# No space after `=`. This file is sourced by frrinit.sh, and `VAR=  "x"` in
# shell assigns VAR empty and then runs `  "x"` as a command — which is
# exactly what happened:
#
#   /etc/frr/daemons: line 18:   -A 127.0.0.1 -s 90000000: command not found
#   /etc/frr/daemons: line 19:   -A 127.0.0.1: command not found
#
# FRR started anyway, so this looked harmless, and both daemons silently ran
# with no options at all. Losing `-A 127.0.0.1` means the VTY is not bound to
# loopback; losing `-s 90000000` leaves zebra on the default netlink receive
# buffer, which is the one thing a fabric with tens of thousands of
# interfaces cannot afford — route sync starts failing under exactly the load
# this config exists to carry.
zebra_options="-A 127.0.0.1 -s 90000000"
bgpd_options="-A 127.0.0.1"
"""


#: vtysh complains on stderr for every command when this file is missing,
#: and integrated-vtysh-config is the mode frr.conf already assumes.
_VTYSH_CONF = "service integrated-vtysh-config\n"


def frr_seed_files(daemons: str, frr_conf: str) -> dict[str, str]:
    """The same config as `_frr_installer`, as files rather than a script.

    The script exists because applying config to a *running* node is the only
    thing write_file() can do, and it has to restart FRR to pick up a changed
    daemons file. Seeding these before the container starts avoids all of
    that: `frrinit.sh start` reads the daemons file we put there, so bgpd
    comes up enabled and configured the first time, with no restart and no
    reconvergence.

    Both are emitted. A node created before this existed, or on a runtime
    with no seeding, still has the script to fall back on.
    """
    return {
        "/etc/frr/daemons": daemons if daemons.endswith("\n") else daemons + "\n",
        "/etc/frr/frr.conf": frr_conf if frr_conf.endswith("\n") else frr_conf + "\n",
        "/etc/frr/vtysh.conf": _VTYSH_CONF,
    }


def seed_files_from_installer(script: str) -> dict[str, str]:
    """Recover the files an installer script writes, for seeding instead.

    Deliberately in this module, next to the function that writes the script:
    the heredoc markers are ours, not a guess at someone else's format, and
    keeping both sides in one file means a change to one is a change to the
    other in the same diff.

    Returns {} for anything that is not one of our FRR installers, so a
    hand-written startup_config is left alone rather than half-understood.
    """
    out: dict[str, str] = {}
    for marker, path in (
        ("EOF_DAEMONS", "/etc/frr/daemons"),
        ("EOF_FRR", "/etc/frr/frr.conf"),
    ):
        opener = f"<<'{marker}'\n"
        start = script.find(opener)
        if start == -1:
            return {}
        start += len(opener)
        end = script.find(f"\n{marker}\n", start)
        if end == -1:
            return {}
        body = script[start:end]
        out[path] = body if body.endswith("\n") else body + "\n"
    out["/etc/frr/vtysh.conf"] = _VTYSH_CONF
    return out
